Temný hvozd noci, tajemná a neblahá oblast, leží daleko na severu Utopie a vrhá děsivý stín na severní části kontinentu. Tento prastarý les, zastrčený na západ od severního konce Pouště lebek, je zahalen tajemnou aurou a jeho tajemství jsou skryta před zvědavýma očima světa.

Vstup do Temného hvozdu je jako vstoupit do říše nedotčené časem. Tyčící se stromy se sukovitými větvemi se proplétají a vytvářejí hustý baldachýn, který zahaluje lesní půdu v ​​věčném soumraku. Vzduch je těžký nadpozemským klidem, přerušovaným jen občasným šustěním listí nebo strašidelným voláním neviditelných tvorů. Zbloudilé paprsky měsíčního světla pronikají hustým listím a vrhají na pokroucené kmeny éterickou záři.

Zdá se, že samotná podstata Temného hvozdu popírá přírodní zákony. Stromy, starověké strážce, které stály po staletí, nesou známky neznámého původu – runy a symboly vyryté do jejich kůry, naznačující zapomenuté kouzlo, které prostupuje lesy. Pod nohama je měkká půda, koberec z mechu a spadaného listí, který tlumí kroky a dodává pocit izolace a tajemství.

Procházet labyrintovými cestami Temného hvozdu je nebezpečné úsilí. Vzduch šeptá s neviditelným nebezpečím a samotné stíny jako by se posouvaly a svíjely. Dokonce i ostřílení zálesáci, mistři průzkumu, přistupují k tomuto záhadnému lesu se směsí úžasu a strachu. Legendy hovoří o nepolapitelných duších, spektrálních bytostech, které straší v srdci lesa, strážcích tajemství, které znají jen nejstarší stromy.

Jak se do Temného hvozdu snáší noc, atmosféra se stává mnohem tajemnější. Slabé záblesky světélkující flóry, nedotčené slunečním zářením, osvětlují okolí nadpozemskou září. Vzduch rezonuje s melodickým hučením, jako by samotný les ožil prastarou silou, která pulzuje jeho kořeny.

Málokdo se odváží vydat se hluboko do srdce Temného hvozdu, kde jsou tajemství lesů prý nejpřísněji střežena. Zdá se, že samotný vzduch nese nevyslovené varování, varující vetřelce, aby respektovali rovnováhu přírody a magie, která prostupuje tuto začarovanou říši. Temný les noci je svědectvím o neznámých silách, které číhají v zákoutích Utopie, místo, kde se stírá hranice mezi realitou a mystikou a kde ti nejodvážnější přešlapují zlehka, uznávajíce úctu k dávnému a tajemnému .