%s becomes another greasy stain on the desert sands.
%s departs the land of the living.
%s travels to the next world courtesy of %s.
%s lead a heroic, but brief life.
The life of %s was cut short by %s.
%s is now dancing with the reaper.
%s wins a free trip across the styx from %s.
%s takes a one way trip to Hades.
%s, worried, looks down and sees his corpse.
%s is carried off by the Valkyries.
Let %s's name be praised.
%s no longer resides within the mortal realm.
%s becomes the corpus delecti.
%s is sent to the pearly gates by %s.
%s is introduced to death by %s.
%s now understands the agony of defeat.
Nice try %s, but no cigar.
%s becomes a part of history.
%s suffers an untimely death at the hands of %s.
%s gets assrammed with a large spikey stick by %s.
%s was chopped into pieces by %s.
The legend of %s was ended rather suddenly by %s
%s is now a stain on %s's weapon.
The remains of %s are boiled in a pot along with vegetables, herbs and seasoning and are eaten by %s.
%s is now an extension of %s's weapon.
The insects now have %s to themselves.
%s's corpse is now suffering at the hands of %s.
%s floats around in the insides of %s
%s expires due to %s's blow.
%s died from an unknown disease from the weapon of %s
%s is now an ex-player... has ceased to be... is no more!
Monkey %s has gone to heaven
*** %s was kicked from #Real-Life by %s (llama farmer)
%s is now partying with Kurt Cobain, elvis and the big bopper.
%s wanders into the light with a helping hand from %s
%s gets recycled by %s
%s becomes a greasy smear on %s's boot
%s is now a greasy puddle.
%s's grave is danced on by %s, with great merriment
%s has a hole in his stomach!
%s finds themselves both diced AND sliced
No guts, no glory. %s's guts now belong to %s
%s looks at the grass from below
%s goes to look if god really exists
%s goes the fast way to hell
And there was much rejoicing as %s left the mortal coil
%s was terminated with extreme predjudice
%s simply expires
%s was mortally wounded
%s falls to the ground oozing
Pause a moment and mourn the loss of %s
%s passes through the Dred Portal
All your %s are belong to %s.

